blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/coder-hxl/x-crawl/discussions
    about: Use GitHub discussions for message-board style questions and discussions.
